services:
  db:
    image: postgres:16
    container_name: it_tracker_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: it_tracker
    ports:
      - "5432:5432"